# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.showcase_v1beta1.proto import testing_pb2 as google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2


class TestingStub(object):
  """A service to facilitate running discrete sets of tests
  against Showcase.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateSession = channel.unary_unary(
        '/google.showcase.v1beta1.Testing/CreateSession',
        request_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.CreateSessionRequest.SerializeToString,
        response_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.Session.FromString,
        )
    self.GetSession = channel.unary_unary(
        '/google.showcase.v1beta1.Testing/GetSession',
        request_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.GetSessionRequest.SerializeToString,
        response_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.Session.FromString,
        )
    self.ListSessions = channel.unary_unary(
        '/google.showcase.v1beta1.Testing/ListSessions',
        request_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ListSessionsRequest.SerializeToString,
        response_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ListSessionsResponse.FromString,
        )
    self.DeleteSession = channel.unary_unary(
        '/google.showcase.v1beta1.Testing/DeleteSession',
        request_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.DeleteSessionRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.ReportSession = channel.unary_unary(
        '/google.showcase.v1beta1.Testing/ReportSession',
        request_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ReportSessionRequest.SerializeToString,
        response_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ReportSessionResponse.FromString,
        )
    self.ListTests = channel.unary_unary(
        '/google.showcase.v1beta1.Testing/ListTests',
        request_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ListTestsRequest.SerializeToString,
        response_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ListTestsResponse.FromString,
        )
    self.DeleteTest = channel.unary_unary(
        '/google.showcase.v1beta1.Testing/DeleteTest',
        request_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.DeleteTestRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.VerifyTest = channel.unary_unary(
        '/google.showcase.v1beta1.Testing/VerifyTest',
        request_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.VerifyTestRequest.SerializeToString,
        response_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.VerifyTestResponse.FromString,
        )


class TestingServicer(object):
  """A service to facilitate running discrete sets of tests
  against Showcase.
  """

  def CreateSession(self, request, context):
    """Creates a new testing session.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSession(self, request, context):
    """Gets a testing session.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListSessions(self, request, context):
    """Lists the current test sessions.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteSession(self, request, context):
    """Delete a test session.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReportSession(self, request, context):
    """Report on the status of a session.
    This generates a report detailing which tests have been completed,
    and an overall rollup.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListTests(self, request, context):
    """List the tests of a sessesion.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTest(self, request, context):
    """Explicitly decline to implement a test.

    This removes the test from subsequent `ListTests` calls, and
    attempting to do the test will error.

    This method will error if attempting to delete a required test.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VerifyTest(self, request, context):
    """Register a response to a test.

    In cases where a test involves registering a final answer at the
    end of the test, this method provides the means to do so.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TestingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateSession': grpc.unary_unary_rpc_method_handler(
          servicer.CreateSession,
          request_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.CreateSessionRequest.FromString,
          response_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.Session.SerializeToString,
      ),
      'GetSession': grpc.unary_unary_rpc_method_handler(
          servicer.GetSession,
          request_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.GetSessionRequest.FromString,
          response_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.Session.SerializeToString,
      ),
      'ListSessions': grpc.unary_unary_rpc_method_handler(
          servicer.ListSessions,
          request_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ListSessionsRequest.FromString,
          response_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ListSessionsResponse.SerializeToString,
      ),
      'DeleteSession': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteSession,
          request_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.DeleteSessionRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'ReportSession': grpc.unary_unary_rpc_method_handler(
          servicer.ReportSession,
          request_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ReportSessionRequest.FromString,
          response_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ReportSessionResponse.SerializeToString,
      ),
      'ListTests': grpc.unary_unary_rpc_method_handler(
          servicer.ListTests,
          request_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ListTestsRequest.FromString,
          response_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.ListTestsResponse.SerializeToString,
      ),
      'DeleteTest': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTest,
          request_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.DeleteTestRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'VerifyTest': grpc.unary_unary_rpc_method_handler(
          servicer.VerifyTest,
          request_deserializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.VerifyTestRequest.FromString,
          response_serializer=google_dot_showcase__v1beta1_dot_proto_dot_testing__pb2.VerifyTestResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'google.showcase.v1beta1.Testing', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
